apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-dispatch
  labels:
    service: dispatch
  annotations:
    greymatter.io/inject-sidecar-to: "55555"  
spec:
  replicas: 1
  selector:
    matchLabels:
      service: dispatch
  template:
    metadata:
      labels:
        service: dispatch
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: dispatch
        image: {{ .Values.image.repo }}/rs-dispatch:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          # agent networking access
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: AMQP_HOST
            value: "127.0.0.1"
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
