apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs_mysql
  labels:
    service: rs_mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rs_mysql
  template:
    metadata:
      labels:
        service: rs_mysql
      annotations:
        greymatter.io/inject-sidecar-to: "3306"
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: mysql
        image: {{ .Values.image.repo }}/rs-mysql-db:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # added for Istio
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 700Mi
      restartPolicy: Always
