apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    service: payment
    stage: prod
  annotations:
    greymatter.io/inject-sidecar-to: "9080"    
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment
      stage: prod
  template:
    metadata:
      labels:
        service: payment
        stage: prod
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: payment
        image: {{ .Values.image.repo }}/rs-payment:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # agent networking access
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: SHOP_PAYMENT_PORT
            value: "9080"
          - name: CART_HOST
            value: "127.0.0.1"
          - name: USER_HOST
            value: "127.0.0.1"
          - name: AMQP_HOST
            value: "127.0.0.1"
          {{- if .Values.payment.gateway }}
          - name: PAYMENT_GATEWAY
            value: {{ .Values.payment.gateway }}
          {{- end }}
        ports:
        - containerPort: 9080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
            - mountPath: /app/payment.ini
              name: payment-uwsgi
              subPath: payment.ini
      restartPolicy: Always
      volumes:
        - name: payment-uwsgi
          configMap:
            defaultMode: 420
            name: payment-uwsgi